persistence false
allow_anonymous false
password_file /run/kth-devops/password_file
acl_file /mosquitto/config/acl

listener 1883
protocol mqtt
allow_anonymous false

listener 9001
protocol websockets
allow_anonymous false
